// Shadcn UI component re-exports
// These are generated by shadcn-ui CLI in a real project.
// Here we provide the typed stubs that match the shadcn API.

export { Button, buttonVariants } from "./button";
export { Input } from "./input";
export { Label } from "./label";
export { Textarea } from "./textarea";
export { Badge, badgeVariants } from "./badge";
export { Avatar, AvatarFallback, AvatarImage } from "./avatar";
export { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "./card";
export { Separator } from "./separator";
export { Tabs, TabsContent, TabsList, TabsTrigger } from "./tabs";
export { Progress } from "./progress";
export { Switch } from "./switch";
export { Checkbox } from "./checkbox";
export { Select, SelectContent, SelectGroup, SelectItem, SelectLabel, SelectTrigger, SelectValue } from "./select";
export {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuPortal,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuTrigger,
} from "./dropdown-menu";
export {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogOverlay,
  DialogPortal,
  DialogTitle,
  DialogTrigger,
} from "./dialog";
export { Collapsible, CollapsibleContent, CollapsibleTrigger } from "./collapsible";
export { ScrollArea, ScrollBar } from "./scroll-area";
export { Skeleton } from "./skeleton";
export { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "./tooltip";
